user:
  name:
    max_length: 20

  email:
    max_length: 255

  phone:
    min_length: 10
    max_length: 15

  address:
    min_length: 8

product:
  product_name:
    max_length: 35

  detail:
    min_length: 14
    max_length: 300

category:
  category_name:
    max_length: 16
  search: { "Apple": 1, "Samsung": 2, "Huawei": 3, "Dell": 4 }
